# Generated by Django 5.1.4 on 2025-12-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('origem_cliente', models.CharField(max_length=50)),
                ('servico', models.CharField(max_length=100)),
                ('data_inicio_atendimento', models.DateField(auto_now_add=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Em consulta', max_length=50)),
                ('consulta_realizada', models.BooleanField(default=False)),
                ('data_consulta', models.DateField(blank=True, null=True)),
                ('valor_consulta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_pagamento_entrada', models.DateField(blank=True, null=True)),
                ('tipo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
